# Generated by Django 4.1.3 on 2022-11-03 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webtoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoon',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
