# Generated by Django 4.1.3 on 2022-11-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webtoon", "0002_alter_webtoon_bookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webtoon",
            name="day",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="webtoon",
            name="genre",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="webtoon",
            name="story",
            field=models.TextField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="webtoon",
            name="thumbnail_url",
            field=models.URLField(default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="webtoon",
            name="title",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="webtoon",
            name="webtoon_url",
            field=models.URLField(default="", max_length=300),
        ),
    ]
