# Generated by Django 4.1.3 on 2022-11-03 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webtoon', '0003_alter_webtoon_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoon',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
