# Generated by Django 4.1.3 on 2022-11-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webtoon", "0003_alter_webtoon_day_alter_webtoon_genre_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=70)),
            ],
            options={"db_table": "genre",},
        ),
        migrations.RemoveField(model_name="webtoon", name="genre",),
        migrations.AddField(
            model_name="webtoon",
            name="genre",
            field=models.ManyToManyField(related_name="genre_set", to="webtoon.genre"),
        ),
    ]
