# Generated by Django 4.1.3 on 2022-11-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webtoon", "0004_genre_remove_webtoon_genre_webtoon_genre"),
    ]

    operations = [
        migrations.AlterModelTable(name="webtoon", table="webtoon",),
    ]
